## Import the Dataset

In [ ]:
import pandas as pd

train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("total_.csv", skiprows = 1)

In [7]:
train_df.head()

,id,text,Q0_RELEVANT,Q1_mood_of_speaker,Q2_primary_target_of_opinion,Q3_emotion_of_speaker_towards_PTO
0,902112185685565441,Angela Merkel insists she has no regrets over ...,YES,UNKNOWN,ANGELA MERKEL,UNKNOWN
1,902612931560574977,Lol made a friend my first day at csu & now sh...,NO,NaN,NaN,NaN
2,902593242390286337,@Model3Owners and yet Merkel said combustion e...,YES,NEGATIVE,ANGELA MERKEL,NEGATIVE
3,902365247075479553,@salmaankhwaja Partly Cloudy in #Karachi with ...,NO,NaN,NaN,NaN
4,902062462710812672,#GermanyDecidsðŸ‡©ðŸ‡ª: Too many think pieces on Mer...,YES,UNKNOWN,ANGELA MERKEL,NEGATIVE

In [8]:
test_df.head()

,ï»¿id,time,created_at,from_user_name,text,filter_level,possibly_sensitive,withheld_copyright,withheld_scope,truncated,...,from_user_utcoffset,from_user_timezone,from_user_lang,from_user_tweetcount,from_user_followercount,from_user_friendcount,from_user_favourites_count,from_user_listed,from_user_withheld_scope,from_user_created_at
0,880939004610347010,1498867200,2017-07-01 00:00:00,ChrisJov155Bot,Merkel Ã¼ber Telegram fÃ¼r die positive RÃ¼ckmeld...,low,NaN,NaN,NaN,0,...,7200,Berlin,de,7,4,4,1,0,NaN,2017-06-29 17:55:33
1,880939021983072256,1498867204,2017-07-01 00:00:04,NorwayHitSongs,Dagens hit YouTube Video i Norge.(Today's hit ...,low,0,NaN,NaN,0,...,-36000,Hawaii,en,42016,1174,1471,0,7,NaN,2011-08-04 02:09:00
2,880939026118791168,1498867205,2017-07-01 00:00:05,richieevansx,Mr. Probz - Waves (Robin Schulz Remix Radio Ed...,low,0,NaN,NaN,0,...,NaN,NaN,en,867,24,66,178,0,NaN,2010-10-01 12:45:04
3,880939026877960192,1498867205,2017-07-01 00:00:05,asivnzlalgbti,"Alemania legaliza el matrimonio homosexual, in...",low,0,NaN,NaN,0,...,NaN,NaN,es,21,9,81,0,0,NaN,2017-04-01 00:21:50
4,880939038026342400,1498867208,2017-07-01 00:00:08,teammaskey,RT @IEatAdelaide: Merkel opposed it but still ...,low,NaN,NaN,NaN,0,...,-25200,Pacific Time (US & Canada),en,23868,605,749,21451,116,NaN,2013-05-27 08:37:06

## Remove Null values from training data

In [9]:
train_df.dropna(subset=['text','Q0_RELEVANT'], inplace=True)

In [10]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 998 entries, 0 to 999
Data columns (total 6 columns):
id                                   998 non-null int64
text                                 998 non-null object
Q0_RELEVANT                          998 non-null object
Q1_mood_of_speaker                   558 non-null object
Q2_primary_target_of_opinion         558 non-null object
Q3_emotion_of_speaker_towards_PTO    558 non-null object
dtypes: int64(1), object(5)
memory usage: 54.6+ KB

In [11]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7760991 entries, 0 to 7760990
Data columns (total 36 columns):
ï»¿id                            object
time                           object
created_at                     object
from_user_name                 object
text                           object
filter_level                   object
possibly_sensitive             object
withheld_copyright             object
withheld_scope                 object
truncated                      object
retweet_count                  object
favorite_count                 object
lang                           object
to_user_name                   object
in_reply_to_status_id          object
quoted_status_id               object
source                         object
location                       object
lat                            object
lng                            object
from_user_id                   object
from_user_realname             object
from_user_verified             object
from_user_description          object
from_user_url                  object
from_user_profile_image_url    object
from_user_utcoffset            object
from_user_timezone             object
from_user_lang                 object
from_user_tweetcount           object
from_user_followercount        object
from_user_friendcount          object
from_user_favourites_count     object
from_user_listed               object
from_user_withheld_scope       object
from_user_created_at           object
dtypes: object(36)
memory usage: 2.1+ GB

In [13]:
test_df = test_df.loc[test_df['lang'] == 'en']
en_test_df = test_df[['created_at', 'text']]
print(en_test_df.shape)
en_test_df.head()

(2021752, 2)

            created_at                                               text
1  2017-07-01 00:00:04  Dagens hit YouTube Video i Norge.(Today's hit ...
2  2017-07-01 00:00:05  Mr. Probz - Waves (Robin Schulz Remix Radio Ed...
4  2017-07-01 00:00:08  RT @IEatAdelaide: Merkel opposed it but still ...
6  2017-07-01 00:00:15  CSU's Adam Ward, been the head coach of the Bu...
7  2017-07-01 00:00:16  Putin and Merkel have discussed the agenda of ...

In [33]:
time_df = pd.DataFrame(en_test_df[['created_at']])
time_df = time_df.reset_index(drop=True)
time_df.head()

            created_at
0  2017-07-01 00:00:04
1  2017-07-01 00:00:05
2  2017-07-01 00:00:08
3  2017-07-01 00:00:15
4  2017-07-01 00:00:16

## Data Cleaning

In [19]:
import re
def clean_tweet(tweet):
        '''
        Utility function to clean tweet text by removing links, special characters
        using simple regex statements.
        '''
        return ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)", " ", tweet).split())

In [20]:
def parse_data(tweets):
    parsed_tweets = []
    cnt = 0
    for tweet in tweets:
        cnt += 1
        # empty dictionary to store required params of a tweets
        parsed_tweet = {}
        # cleaning text of tweet
        parsed_tweet['text'] = clean_tweet(tweet)
        parsed_tweets.append(parsed_tweet)
    print ("Cleaned data for %d tweet" % cnt)
    return parsed_tweets

In [36]:
clean_en_test_df = pd.DataFrame(parse_data(en_test_df['text'].tolist()))

Cleaned data for 2021752 tweet

In [39]:
clean_en_test_df = pd.concat([time_df, clean_en_test_df], axis=1)

In [40]:
clean_train_df = pd.DataFrame(parse_data(train_df['text'].tolist()))

Cleaned data for 998 tweet

In [43]:
selected_train_df = train_df[['Q0_RELEVANT', 'Q1_mood_of_speaker']].reset_index(drop=True)

In [44]:
clean_train_df = pd.concat([clean_train_df, selected_train_df], axis=1)

In [45]:
clean_train_df.head()

,text,Q0_RELEVANT,Q1_mood_of_speaker
0,Angela Merkel insists she has no regrets over ...,YES,UNKNOWN
1,Lol made a friend my first day at csu now she ...,NO,NaN
2,and yet Merkel said combustion engine will be ...,YES,NEGATIVE
3,Partly Cloudy in Karachi with Wind spd 0 83 Hu...,NO,NaN
4,GermanyDecids Too many think pieces on Merkel ...,YES,UNKNOWN

## Machine Learning to predict Q0 and Q1 for Test Dataset

In [46]:
column_dict = {'Q0': 'Q0_RELEVANT',
               'Q1': 'Q1_mood_of_speaker'}

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

def train_and_predict(df_train, df_test, column="Q0",verbose=True):
    cv = TfidfVectorizer(min_df=1, stop_words='english')
    
    mask = (df_train[column_dict["Q0"]] == df_train[column_dict["Q0"]])
    if column== "Q0":
        df_train_ = df_train
    else:
        mask = df_train[column_dict["Q0"]] == "YES"
        df_train_ = df_train[mask]
        
    tweet_train = cv.fit_transform(df_train_['text'])
    label_train = df_train_[column_dict[column]]
    classifier = RandomForestClassifier(50, random_state=4, verbose=verbose)
    classifier.fit(tweet_train, label_train)
    
    tweet_test = cv.transform(df_test["text"])
    return classifier.predict(tweet_test)

In [49]:
#include columns from original dataset
data = {"text":clean_en_test_df["text"],
        "created_at":pd.to_datetime(clean_en_test_df["created_at"])
       }

for column in column_dict.keys():
    data[column] = train_and_predict(df_train = clean_train_df, df_test = clean_en_test_df, column = column)

[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:   22.4s finished
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:    0.1s finished
[Parallel(n_jobs=1)]: Done  50 out of  50 | elapsed:   19.5s finished

In [52]:
df_predictions = pd.DataFrame(data)
for i, row in df_predictions.iterrows():
    if row["Q0"]=="NO" :
        df_predictions.at[i,"Q1"] = "NULL"
df_predictions

,Q0,Q1,created_at,text
0,NO,NULL,2017-07-01 00:00:04,Dagens hit YouTube Video i Norge Today s hit Y...
1,NO,NULL,2017-07-01 00:00:05,Mr Probz Waves Robin Schulz Remix Radio Edit
2,YES,UNKNOWN,2017-07-01 00:00:08,RT Merkel opposed it but still brought it on M...
3,NO,NULL,2017-07-01 00:00:15,CSU s Adam Ward been the head coach of the Buc...
4,YES,UNKNOWN,2017-07-01 00:00:16,Putin and Merkel have discussed the agenda of ...
5,NO,NULL,2017-07-01 00:00:21,LCH issues Area Forecast Discussion AFD
6,NO,NULL,2017-07-01 00:00:21,The fact finding report is just a recommendati...
7,YES,UNKNOWN,2017-07-01 00:00:26,Biatch slap him No more knights in shining arm...
8,YES,UNKNOWN,2017-07-01 00:00:34,RT So what did you do on Friday PM Merkel had ...
9,YES,UNKNOWN,2017-07-01 00:00:38,RT Cathy ART OF THE DEAL MERKEL CAVES TO PRESI...
10,YES,UNKNOWN,2017-07-01 00:00:39,People This Fool is as bad as Merkel May were ...
11,YES,UNKNOWN,2017-07-01 00:00:41,RT Angela Merkel set herself on a collision co...
12,YES,UNKNOWN,2017-07-01 00:00:42,RT and to be honest mrs merkel thank you for n...
13,YES,UNKNOWN,2017-07-01 00:00:47,RT SURRENDER Merkel Just Caved to Trump IT S G...
14,YES,UNKNOWN,2017-07-01 00:01:01,RT BREAKING Germany has been conquered 1st tim...
15,NO,NULL,2017-07-01 00:01:03,RT Today AFD was honored to rename Station 9 a...
16,YES,UNKNOWN,2017-07-01 00:01:04,RT This isn t at all surprising The Angela Mer...
17,YES,UNKNOWN,2017-07-01 00:01:07,Remember just because Angela Merkel is against...
18,YES,UNKNOWN,2017-07-01 00:01:10,Merkel is a sociopathic communist using the Is...
19,YES,UNKNOWN,2017-07-01 00:01:18,RT DUMBEST WOMAN ON EARTH Angela Merkel says I...
20,YES,UNKNOWN,2017-07-01 00:01:21,NotFakeNews Being respect by Merkel is not a c...
21,YES,UNKNOWN,2017-07-01 00:01:23,RT SURRENDER Angela Merkel Just Caved to Trump...
22,YES,UNKNOWN,2017-07-01 00:01:37,SURRENDER Angela Merkel Just Caved to Trump an...
23,YES,UNKNOWN,2017-07-01 00:01:40,RT MERKEL s Germany now joins France as citize...
24,YES,UNKNOWN,2017-07-01 00:01:43,RT Number of tweets world leaders made in 2017...
25,YES,UNKNOWN,2017-07-01 00:01:46,RT Recall US UK liberals brainlessly bleating ...
26,NO,NULL,2017-07-01 00:01:47,RT That s Cemile Giousouf She s a Muslim woman...
27,YES,UNKNOWN,2017-07-01 00:01:50,Yes It s amazing that the vote for same sex ma...
28,YES,UNKNOWN,2017-07-01 00:01:58,Angela Merkel voted against gay marriage
29,YES,UNKNOWN,2017-07-01 00:01:59,RT Cathy ART OF THE DEAL MERKEL CAVES TO PRESI...
...,...,...,...,...
2021722,YES,UNKNOWN,2017-08-31 23:56:58,RT When bells ring in the MerkelLand Merkel re...
2021723,YES,UNKNOWN,2017-08-31 23:56:58,RT You think Trump isn t liked Friend from Ger...
2021724,YES,UNKNOWN,2017-08-31 23:57:03,RT Welcome to Merkel s culturally enriched Eur...
2021725,NO,NULL,2017-08-31 23:57:04,RT Fuck em I demand a hearing into Debra Wasse...
2021726,YES,UNKNOWN,2017-08-31 23:57:05,RT EU living in Harmony Poland to be STRIPPED ...
2021727,NO,NULL,2017-08-31 23:57:19,RT Following news of Seattle s settlement with...
2021728,YES,UNKNOWN,2017-08-31 23:57:26,of Europe For sure Merkel must go Want to see ...
2021729,NO,NULL,2017-08-31 23:57:36,The latest The Hans Carlos Hofmann Daily Thank...
2021730,YES,UNKNOWN,2017-08-31 23:57:48,RT Welcome to Merkel s culturally enriched Eur...
2021731,YES,UNKNOWN,2017-08-31 23:57:50,RT pundit Important And Right Merkel Has No Re...
2021732,YES,UNKNOWN,2017-08-31 23:57:52,Merkel Must Leave
2021733,NO,NULL,2017-08-31 23:57:56,GJT issues Area Forecast Discussion AFD
2021734,NO,NULL,2017-08-31 23:58:00,Fenders SPD Panniers Oddly enough I have none ...
2021735,NO,NULL,2017-08-31 23:58:11,RT Less than 24 hours away from at the new CSU...
2021736,YES,UNKNOWN,2017-08-31 23:58:31,RT More than 1 000 complaints filed against Me...
2021737,YES,UNKNOWN,2017-08-31 23:58:43,RT rant Prosecutors Have Rejected 1 000 High T...
2021738,YES,UNKNOWN,2017-08-31 23:58:47,RT Mom would you like it if candy ruled the wo...
2021739,YES,UNKNOWN,2017-08-31 23:58:49,RT When bells ring in the MerkelLand Merkel re...
2021740,NO,NULL,2017-08-31 23:58:55,MQT issues Area Forecast Discussion AFD
2021741,NO,NULL,2017-08-31 23:58:58,RT Fuck em I demand a hearing into Debra Wasse...
2021742,NO,NULL,2017-08-31 23:58:59,RT I m at Csu
2021743,YES,UNKNOWN,2017-08-31 23:59:05,Merkel Vows To Open Germany To More Invaders
2021744,NO,NULL,2017-08-31 23:59:05,RT I m at Csu
2021745,NO,NULL,2017-08-31 23:59:10,RT Fuck em I demand a hearing into Debra Wasse...
2021746,NO,NULL,2017-08-31 23:59:29,no mention of CU CSU sad
2021747,YES,UNKNOWN,2017-08-31 23:59:31,RT Welcome to Merkel s culturally enriched Eur...
2021748,NO,NULL,2017-08-31 23:59:32,I m reading The Complete Peanuts Vol 5 by Char...
2021749,NO,NULL,2017-08-31 23:59:43,RT Hahn SPD OFFs responded 2 serve R SSD CHP f...
2021750,YES,UNKNOWN,2017-08-31 23:59:47,RT Germany s AfD has hired ad agency Harris Me...
2021751,YES,UNKNOWN,2017-08-31 23:59:50,RT of Europe Prosecutors Have Rejected 1 000 H...

In [53]:
df_predictions.Q1.value_counts()

UNKNOWN       1532427
NULL           472673
POSITIVE        14519
NEGATIVE         2128
BOTH/MIXED          5
Name: Q1, dtype: int64

In [56]:
df_predictions.Q0.value_counts()

YES    1549079
NO      472673
Name: Q0, dtype: int64

In [54]:
clean_train_df.Q1_mood_of_speaker.value_counts()

UNKNOWN       486
NEGATIVE       48
POSITIVE       20
BOTH/MIXED      4
Name: Q1_mood_of_speaker, dtype: int64

In [55]:
train_df.Q2_primary_target_of_opinion.value_counts()

ANGELA MERKEL        501
AFD                   20
MARTIN SCHULZ         15
SPD                    8
CDU                    6
ANGELA  MERKEL         3
DIE LINKE              2
CSU                    1
ALEXANDER GAULAND      1
MERKEL                 1
Name: Q2_primary_target_of_opinion, dtype: int64

__Write the predicted dataset to csv file for further use__

In [58]:
df_predictions.to_csv("~/GermanElections.csv", index=False)